#!/usr/bin/env python3
"""
Generate rtl/sc_selftest_rom.v: the program run by the on-board self-test
sequencer (sc_selftest.v). It drives the SecureCrypto registers exactly like
the HPS driver would and compares results with official KAT values.

Usage: python3 gen_selftest.py <LWC_AEAD_KAT_128_128.txt> <pyascon_dir> <out.v>

Instruction word = {op[2:0], addr[6:0], data[31:0], mask[31:0]}  (74 bits)
  0 END                         stop, report pass/fail
  1 WR     addr data            bus write
  2 WAIT   addr mask            read until (rd & mask) != 0
  3 RDCMP  addr data mask       read, error if (rd & mask) != data
  4 WRSW0  addr data            bus write only if SW[0] = 1 (fault injection)
  5 RDSW1  addr                 bus read only if SW[1] = 1 (key-read attempt)
"""
import sys

kat_path, pyascon_dir, out_path = sys.argv[1:4]
sys.path.insert(0, pyascon_dir)
import ascon  # noqa: E402

A = dict(CTRL=1, STATUS=2, BLK=3, NONCE=4, DIN=8, DOUT=12, TAGIN=16, TAGOUT=20,
         KEYWR=24, KEYRD=28, SEED=32, FCFG=33, DBUF=64)
ST_RDY, ST_DONE, ST_TAGOK = 1 << 1, 1 << 2, 1 << 3

vecs = {}
for rec in open(kat_path).read().strip().split("\n\n"):
    d = {}
    for line in rec.splitlines():
        k, _, v = line.partition(" =")
        d[k.strip()] = v.strip()
    ad, pt = bytes.fromhex(d["AD"]), bytes.fromhex(d["PT"])
    vecs[(len(ad), len(pt))] = (bytes.fromhex(d["Key"]), bytes.fromhex(d["Nonce"]),
                                ad, pt, bytes.fromhex(d["CT"]))

prog = []


def op(o, addr=0, data=0, mask=0):
    prog.append((o, addr, data & 0xFFFFFFFF, mask & 0xFFFFFFFF))


def w32(b, i):
    return int.from_bytes(b[4 * i:4 * i + 4], "little")


def blocks(b):
    b = b + bytes((len(b) // 16 + 1) * 16 - len(b))
    return [b[i:i + 16] for i in range(0, len(b), 16)]


def bytemask(n):          # mask for word i of a block holding n bytes
    return [((1 << (8 * max(0, min(4, n - 4 * i)))) - 1) for i in range(4)]


def send(data, is_ad, check_ct=None):
    blks = blocks(data)
    cts = blocks(check_ct) if check_ct is not None else None
    for k, blk in enumerate(blks):
        last = k == len(blks) - 1
        nb = len(data) % 16 if last else 16
        op(2, A["STATUS"], 0, ST_RDY | ST_DONE)
        for i in range(4):
            op(1, A["DIN"] + i, w32(blk, i))
        op(1, A["BLK"], (int(last) << 9) | (int(is_ad) << 8) | (nb if last else 0))
        if cts is not None:
            op(2, A["STATUS"], 0, ST_RDY | ST_DONE)
            m = bytemask(nb)
            for i in range(4):
                op(3, A["DOUT"] + i, w32(cts[k], i) & m[i], m[i])


def run(key, nonce, ad, pt, ctt, fault=False):
    ct, tag = ctt[:-16], ctt[-16:]
    for i in range(4):
        op(1, A["KEYWR"] + i, w32(key, i))
    if fault:     # flip x2 bit 7 after round 5 - only when SW[0] is on
        op(4, A["FCFG"], (2 << 12) | (7 << 16) | (5 << 4) | 1)
    # ---- encrypt
    for i in range(4):
        op(1, A["NONCE"] + i, w32(nonce, i))
    op(1, A["CTRL"], (1 << 3) | (int(len(ad) > 0) << 2) | 1)
    if ad:
        send(ad, True)
    send(pt, False, ct)
    op(2, A["STATUS"], 0, ST_DONE)
    for i in range(4):
        op(3, A["TAGOUT"] + i, w32(tag, i), 0xFFFFFFFF)
    if fault:
        op(1, A["FCFG"], 0)
    # ---- decrypt
    for i in range(4):
        op(1, A["NONCE"] + i, w32(nonce, i))
    for i in range(4):
        op(1, A["TAGIN"] + i, w32(tag, i))
    op(1, A["CTRL"], (1 << 3) | (int(len(ad) > 0) << 2) | 2 | 1)
    if ad:
        send(ad, True)
    send(ct, False)
    op(2, A["STATUS"], 0, ST_DONE)
    op(3, A["STATUS"], ST_TAGOK, ST_TAGOK)
    for k, blk in enumerate(blocks(pt)):
        nb = min(16, len(pt) - 16 * k)
        m = bytemask(nb)
        for i in range(4):
            op(3, A["DBUF"] + 4 * k + i, w32(blk, i) & m[i], m[i])


op(1, A["CTRL"], 1 << 12)                 # clear sticky flags
op(5, A["KEYRD"])                         # key-read attempt if SW[1]
for sel in [(0, 0), (5, 7), (16, 16), (20, 31)]:
    v = vecs[sel]
    assert ascon.ascon_encrypt(v[0], v[1], v[2], v[3]) == v[4]
    run(*v)
run(*vecs[(5, 7)], fault=True)           # fault demo vector (SW[0])
op(0)

with open(out_path, "w") as f:
    f.write("// Generated by tb/gen_selftest.py from the official Ascon-AEAD128 KAT.\n")
    f.write("// Do not edit by hand.\n`timescale 1ns/1ps\n")
    f.write("module sc_selftest_rom (\n    input  wire [9:0]  pc,\n"
            "    output reg  [73:0] insn\n);\n    always @(*) begin\n"
            "        case (pc)\n")
    for i, (o, a, d, m) in enumerate(prog):
        f.write(f"        10'd{i}: insn = {{3'd{o}, 7'd{a}, 32'h{d:08x}, 32'h{m:08x}}};\n")
    f.write("        default: insn = 74'd0;\n        endcase\n    end\nendmodule\n")
print(f"{len(prog)} instructions -> {out_path}")
assert len(prog) < 1024
